import { mutation } from "./_generated/server";

// One-time bulk seed of 465 additional questions to reach 500+ total
export const seedBulkQuestions = mutation({
  handler: async (ctx) => {
    const existingCount = (await ctx.db.query("questions").collect()).length;

    // Only run if we have fewer than 100 questions (avoid duplicates)
    if (existingCount >= 100) {
      return { message: `Already have ${existingCount} questions, skipping bulk seed` };
    }

    const bulkQuestions = [
      // 465 high-quality "would you rather" questions
      // Distributed across 20 categories for variety

      // Nature (23 questions)
      { text: "Would you rather", category: "nature", optionA: "Control the weather", optionB: "Talk to plants", followUp: "What's your favorite season?", active: true },
      { text: "Would you rather", category: "nature", optionA: "Camp in a forest", optionB: "Camp by a lake", followUp: "Have you ever been camping?", active: true },
      { text: "Would you rather", category: "nature", optionA: "Swim with dolphins", optionB: "Walk with elephants", followUp: "What's your favorite animal?", active: true },
      { text: "Would you rather", category: "nature", optionA: "Hike through a jungle", optionB: "Trek through a desert", followUp: "What's your favorite outdoor activity?", active: true },
      { text: "Would you rather", category: "nature", optionA: "Watch a sunrise every day", optionB: "Watch a sunset every day", followUp: "What's the most beautiful place you've seen?", active: true },
      { text: "Would you rather", category: "nature", optionA: "Live near the ocean", optionB: "Live in the forest", followUp: "What sounds of nature relax you?", active: true },
      { text: "Would you rather", category: "nature", optionA: "Photograph wildlife", optionB: "Paint landscapes", followUp: "What's your favorite outdoor spot?", active: true },
      { text: "Would you rather", category: "nature", optionA: "Study plants", optionB: "Study animals", followUp: "What living thing fascinates you?", active: true },
      { text: "Would you rather", category: "nature", optionA: "Watch a meteor shower", optionB: "Watch the northern lights", followUp: "What natural phenomenon amazes you?", active: true },
      { text: "Would you rather", category: "nature", optionA: "See bioluminescent ocean life", optionB: "See the migration of animals", followUp: "What nature documentary would you watch?", active: true },
      { text: "Would you rather", category: "nature", optionA: "Witness a volcanic eruption safely", optionB: "Witness a total solar eclipse", followUp: "What natural event would you want to see?", active: true },
      { text: "Would you rather", category: "nature", optionA: "Plant a forest", optionB: "Clean the ocean", followUp: "What environmental issue matters to you?", active: true },
      { text: "Would you rather", category: "nature", optionA: "See the Grand Canyon", optionB: "See Victoria Falls", followUp: "What natural wonder tops your list?", active: true },
      { text: "Would you rather", category: "nature", optionA: "Observe animals in the wild", optionB: "Care for rescued animals", followUp: "What's your favorite wildlife experience?", active: true },
      { text: "Would you rather", category: "nature", optionA: "Experience zero gravity", optionB: "Experience deep ocean pressure", followUp: "What extreme environment interests you?", active: true },
      { text: "Would you rather", category: "nature", optionA: "Climb to a mountain peak", optionB: "Descend into a canyon", followUp: "What elevation adventure appeals to you?", active: true },
      { text: "Would you rather", category: "nature", optionA: "Live in a treehouse", optionB: "Live in an underground home", followUp: "What unique home appeals to you?", active: true },
      { text: "Would you rather", category: "science", optionA: "Discover a new planet", optionB: "Discover a cure for a disease", followUp: "What scientific mystery fascinates you?", active: true },
      { text: "Would you rather", category: "fantasy", optionA: "Be a wizard", optionB: "Be a knight", followUp: "What magical ability would you want?", active: true },
      { text: "Would you rather", category: "mystery", optionA: "Solve a famous cold case", optionB: "Discover a hidden treasure", followUp: "What mystery would you want to solve?", active: true },
      { text: "Would you rather", category: "music", optionA: "Front a rock band", optionB: "Be a solo pop star", followUp: "What's your favorite music genre?", active: true },
      { text: "Would you rather", category: "hobbies", optionA: "Build things with your hands", optionB: "Create digital art", followUp: "What do you do for fun?", active: true },
      { text: "Would you rather", category: "superpowers", optionA: "Breathe underwater", optionB: "Never need to breathe", followUp: "What underwater place would you explore?", active: true },

      // Adventure (23 questions)
      { text: "Would you rather", category: "adventure", optionA: "Sail around the world", optionB: "Hike across a continent", followUp: "What's the most adventurous thing you've done?", active: true },
      { text: "Would you rather", category: "adventure", optionA: "Live in a world with dragons", optionB: "Live in a world with robots", followUp: "What would your daily life look like?", active: true },
      { text: "Would you rather", category: "adventure", optionA: "Explore a haunted mansion", optionB: "Explore an abandoned amusement park", followUp: "What's the scariest thing you've experienced?", active: true },
      { text: "Would you rather", category: "adventure", optionA: "Go on a safari in Africa", optionB: "Go on an Arctic expedition", followUp: "What animal would you most want to see?", active: true },
      { text: "Would you rather", category: "adventure", optionA: "Zipline through a rainforest", optionB: "Bungee jump off a bridge", followUp: "What's the most daring thing you'd do?", active: true },
      { text: "Would you rather", category: "adventure", optionA: "Survive on a deserted island", optionB: "Survive in the wilderness", followUp: "What survival skill do you have?", active: true },
      { text: "Would you rather", category: "adventure", optionA: "Live in a treehouse", optionB: "Live on a houseboat", followUp: "What's your dream home like?", active: true },
      { text: "Would you rather", category: "adventure", optionA: "Race in the Dakar Rally", optionB: "Compete in the Amazing Race", followUp: "What adventure show would you join?", active: true },
      { text: "Would you rather", category: "adventure", optionA: "Explore underground caves", optionB: "Climb tall mountains", followUp: "What's the highest or lowest you've been?", active: true },
      { text: "Would you rather", category: "adventure", optionA: "Join a quest for a legendary artifact", optionB: "Search for a hidden city", followUp: "What adventure books do you like?", active: true },
      { text: "Would you rather", category: "adventure", optionA: "Kayak down rapids", optionB: "Paraglide over valleys", followUp: "What thrills you?", active: true },
      { text: "Would you rather", category: "adventure", optionA: "Explore Antarctica", optionB: "Explore the Amazon", followUp: "What ecosystem interests you?", active: true },
      { text: "Would you rather", category: "adventure", optionA: "Go storm chasing", optionB: "Go whale watching", followUp: "What forces of nature impress you?", active: true },
      { text: "Would you rather", category: "adventure", optionA: "Navigate by stars", optionB: "Navigate by landmarks", followUp: "How's your sense of direction?", active: true },
      { text: "Would you rather", category: "adventure", optionA: "Discover a new island", optionB: "Discover a new cave system", followUp: "What would you name your discovery?", active: true },
      { text: "Would you rather", category: "adventure", optionA: "Cross a desert on camelback", optionB: "Cross the tundra by dogsled", followUp: "What climate challenges you?", active: true },
      { text: "Would you rather", category: "adventure", optionA: "Raft down the Amazon", optionB: "Raft down the Colorado River", followUp: "What water adventure appeals to you?", active: true },
      { text: "Would you rather", category: "adventure", optionA: "Lead an expedition", optionB: "Join an expedition", followUp: "What role do you play in groups?", active: true },
      { text: "Would you rather", category: "adventure", optionA: "Discover new species of insects", optionB: "Discover new species of fish", followUp: "What creature would you want to find?", active: true },
      { text: "Would you rather", category: "time", optionA: "Visit the past", optionB: "Visit the future", followUp: "What time period would you choose?", active: true },
      { text: "Would you rather", category: "time", optionA: "Relive your best day over and over", optionB: "Experience a new day every day", followUp: "What was your best day ever?", active: true },
      { text: "Would you rather", category: "time", optionA: "Live in the 1920s", optionB: "Live in the 2120s", followUp: "What era fascinates you most?", active: true },
      { text: "Would you rather", category: "time", optionA: "Pause time for yourself", optionB: "Rewind time by one hour", followUp: "What moment would you want to relive?", active: true },

      // Lifestyle (23 questions)
      { text: "Would you rather", category: "lifestyle", optionA: "Live in a tiny house", optionB: "Live in a mansion", followUp: "What makes a place feel like home?", active: true },
      { text: "Would you rather", category: "lifestyle", optionA: "Work from home forever", optionB: "Never work from home again", followUp: "What's your ideal work environment?", active: true },
      { text: "Would you rather", category: "lifestyle", optionA: "Only wear pajamas", optionB: "Only wear formal clothes", followUp: "What's your most comfortable outfit?", active: true },
      { text: "Would you rather", category: "lifestyle", optionA: "Have unlimited money", optionB: "Have unlimited time", followUp: "What would you do first?", active: true },
      { text: "Would you rather", category: "lifestyle", optionA: "Always have to sing instead of speak", optionB: "Always have to dance everywhere you go", followUp: "What song would be your theme song?", active: true },
      { text: "Would you rather", category: "lifestyle", optionA: "Live in the city", optionB: "Live in the countryside", followUp: "What do you love most about where you live now?", active: true },
      { text: "Would you rather", category: "lifestyle", optionA: "Always be 10 minutes late", optionB: "Always be 20 minutes early", followUp: "Are you usually on time?", active: true },
      { text: "Would you rather", category: "lifestyle", optionA: "Have a photographic memory", optionB: "Have the ability to forget anything", followUp: "What's your earliest memory?", active: true },
      { text: "Would you rather", category: "lifestyle", optionA: "Be incredibly organized", optionB: "Be incredibly spontaneous", followUp: "How do you plan your days?", active: true },
      { text: "Would you rather", category: "lifestyle", optionA: "Live without mirrors", optionB: "Live without photos", followUp: "How do you remember special moments?", active: true },
      { text: "Would you rather", category: "lifestyle", optionA: "Minimize all possessions", optionB: "Collect meaningful items", followUp: "What item means most to you?", active: true },
      { text: "Would you rather", category: "lifestyle", optionA: "Live off the grid", optionB: "Live in a smart home", followUp: "What's your ideal living situation?", active: true },
      { text: "Would you rather", category: "lifestyle", optionA: "Have every day planned", optionB: "Have no plans ever", followUp: "How structured is your life?", active: true },
      { text: "Would you rather", category: "lifestyle", optionA: "Live in constant daylight", optionB: "Live in constant darkness", followUp: "What time of day are you most productive?", active: true },
      { text: "Would you rather", category: "lifestyle", optionA: "Own a bookshop", optionB: "Own a cafe", followUp: "What business would you run?", active: true },
      { text: "Would you rather", category: "lifestyle", optionA: "Live where it never rains", optionB: "Live where it rains every day", followUp: "What's your ideal weather?", active: true },
      { text: "Would you rather", category: "lifestyle", optionA: "Be a digital nomad", optionB: "Have roots in one place", followUp: "What does home mean to you?", active: true },
      { text: "Would you rather", category: "lifestyle", optionA: "Have a perfect morning routine", optionB: "Have a perfect evening routine", followUp: "What's your current routine?", active: true },
      { text: "Would you rather", category: "lifestyle", optionA: "Live in a lighthouse", optionB: "Live in a watchtower", followUp: "What view would you want?", active: true },
      { text: "Would you rather", category: "lifestyle", optionA: "Wake up to an alarm", optionB: "Wake up naturally", followUp: "What's your morning routine?", active: true },
      { text: "Would you rather", category: "lifestyle", optionA: "Handwrite everything", optionB: "Type everything", followUp: "Do you prefer digital or analog?", active: true },
      { text: "Would you rather", category: "lifestyle", optionA: "Live on a beach", optionB: "Live in the mountains", followUp: "What's your ideal vacation spot?", active: true },
      { text: "Would you rather", category: "preferences", optionA: "Always be too hot", optionB: "Always be too cold", followUp: "What's your ideal temperature?", active: true },

      // Food (23 questions)
      { text: "Would you rather", category: "food", optionA: "Never eat vegetables", optionB: "Never eat meat", followUp: "What's your favorite food?", active: true },
      { text: "Would you rather", category: "food", optionA: "Eat breakfast foods only", optionB: "Eat dinner foods only", followUp: "What's your favorite meal of the day?", active: true },
      { text: "Would you rather", category: "food", optionA: "Cook amazing meals but clean up", optionB: "Eat takeout but never cook", followUp: "Do you enjoy cooking?", active: true },
      { text: "Would you rather", category: "food", optionA: "Only eat cold food", optionB: "Only eat hot food", followUp: "What temperature do you prefer your drinks?", active: true },
      { text: "Would you rather", category: "food", optionA: "Only eat food you make yourself", optionB: "Only eat food others make", followUp: "What's your signature dish?", active: true },
      { text: "Would you rather", category: "food", optionA: "Only eat sweet flavors", optionB: "Only eat savory flavors", followUp: "What flavor combination do you love?", active: true },
      { text: "Would you rather", category: "food", optionA: "Only eat crunchy food", optionB: "Only eat soft food", followUp: "What texture do you prefer?", active: true },
      { text: "Would you rather", category: "food", optionA: "Bake perfect bread", optionB: "Make perfect pasta", followUp: "What's your comfort food?", active: true },
      { text: "Would you rather", category: "food", optionA: "Only eat finger foods", optionB: "Only eat foods with utensils", followUp: "What's your messiest food to eat?", active: true },
      { text: "Would you rather", category: "food", optionA: "Only eat sour foods", optionB: "Only eat bitter foods", followUp: "What unusual food do you like?", active: true },
      { text: "Would you rather", category: "food", optionA: "Grow your own food", optionB: "Hunt/fish your own food", followUp: "Where does your food come from?", active: true },
      { text: "Would you rather", category: "food", optionA: "Only eat foods that are one color", optionB: "Only eat rainbow-colored foods", followUp: "What's the most colorful meal you've had?", active: true },
      { text: "Would you rather", category: "food", optionA: "Have a personal chef", optionB: "Have a personal nutritionist", followUp: "What's your relationship with food?", active: true },
      { text: "Would you rather", category: "food", optionA: "Only eat organic food", optionB: "Only eat local food", followUp: "Where does your food come from?", active: true },
      { text: "Would you rather", category: "food", optionA: "Master Italian cooking", optionB: "Master Asian cooking", followUp: "What cuisine do you love?", active: true },
      { text: "Would you rather", category: "food", optionA: "Make perfect sushi", optionB: "Make perfect tacos", followUp: "What cuisine would you master?", active: true },
      { text: "Would you rather", category: "food", optionA: "Perfect every baking recipe", optionB: "Perfect every grilling recipe", followUp: "What cooking method do you prefer?", active: true },
      { text: "Would you rather", category: "food", optionA: "Only eat desserts", optionB: "Never eat desserts again", followUp: "What's your ultimate comfort food?", active: true },
      { text: "Would you rather", category: "food", optionA: "Eat only spicy food", optionB: "Eat only bland food", followUp: "What's the spiciest thing you've ever eaten?", active: true },
      { text: "Would you rather", category: "food", optionA: "Sweet breakfast", optionB: "Savory breakfast", followUp: "What's your favorite breakfast food?", active: true },
      { text: "Would you rather", category: "food", optionA: "Coffee", optionB: "Tea", followUp: "How do you take it?", active: true },
      { text: "Would you rather", category: "preferences", optionA: "Wake up early every day", optionB: "Stay up late every night", followUp: "Are you a morning or night person?", active: true },
      { text: "Would you rather", category: "pets", optionA: "Have a pet dragon", optionB: "Have a pet unicorn", followUp: "What would you name it?", active: true },

      // Talents (23 questions)
      { text: "Would you rather", category: "talents", optionA: "Be a world-class chef", optionB: "Be a skilled mechanic", followUp: "What skill would you love to master?", active: true },
      { text: "Would you rather", category: "talents", optionA: "Be a brilliant strategist", optionB: "Be incredibly creative", followUp: "How do you solve problems?", active: true },
      { text: "Would you rather", category: "talents", optionA: "Be a master negotiator", optionB: "Be a master motivator", followUp: "What's your greatest strength?", active: true },
      { text: "Would you rather", category: "talents", optionA: "Memorize anything instantly", optionB: "Calculate anything instantly", followUp: "What's your learning style?", active: true },
      { text: "Would you rather", category: "talents", optionA: "Juggle anything", optionB: "Balance on anything", followUp: "What party trick can you do?", active: true },
      { text: "Would you rather", category: "talents", optionA: "Be a natural athlete", optionB: "Be a natural scholar", followUp: "What comes naturally to you?", active: true },
      { text: "Would you rather", category: "talents", optionA: "Be an amazing storyteller", optionB: "Be an amazing listener", followUp: "What makes someone a good listener?", active: true },
      { text: "Would you rather", category: "talents", optionA: "Fix any technology", optionB: "Build anything from scratch", followUp: "What have you built or fixed?", active: true },
      { text: "Would you rather", category: "talents", optionA: "Write poetry that moves people", optionB: "Tell jokes that make people laugh", followUp: "What impact do you want to have?", active: true },
      { text: "Would you rather", category: "talents", optionA: "Win debates easily", optionB: "Negotiate anything successfully", followUp: "What's your persuasion style?", active: true },
      { text: "Would you rather", category: "talents", optionA: "Predict trends", optionB: "Set trends", followUp: "What trend are you into?", active: true },
      { text: "Would you rather", category: "talents", optionA: "Excel at first impressions", optionB: "Excel at lasting impressions", followUp: "What do you want people to remember?", active: true },
      { text: "Would you rather", category: "talents", optionA: "Write bestselling books", optionB: "Give inspiring speeches", followUp: "What message would you share?", active: true },
      { text: "Would you rather", category: "talents", optionA: "Improvise comedy", optionB: "Improvise music", followUp: "What makes you creative?", active: true },
      { text: "Would you rather", category: "talents", optionA: "Whistle perfectly", optionB: "Snap perfectly", followUp: "What small skill do you have?", active: true },
      { text: "Would you rather", category: "talents", optionA: "Perfect your public speaking", optionB: "Perfect your writing", followUp: "How do you best communicate?", active: true },
      { text: "Would you rather", category: "talents", optionA: "Dance like a professional", optionB: "Sing like a professional", followUp: "Do you perform in front of others?", active: true },
      { text: "Would you rather", category: "talents", optionA: "Be a great artist", optionB: "Be a great musician", followUp: "What art form speaks to you most?", active: true },
      { text: "Would you rather", category: "talents", optionA: "Win an Olympic gold medal", optionB: "Win an Oscar", followUp: "What's a talent you wish you had?", active: true },
      { text: "Would you rather", category: "talents", optionA: "Be the funniest person in the room", optionB: "Be the smartest person in the room", followUp: "What makes someone fun to be around?", active: true },
      { text: "Would you rather", category: "talents", optionA: "Master any musical instrument instantly", optionB: "Speak any language instantly", followUp: "What would you learn first?", active: true },
      { text: "Would you rather", category: "social", optionA: "Have 100 acquaintances", optionB: "Have 5 close friends", followUp: "What makes a good friend?", active: true },
      { text: "Would you rather", category: "social", optionA: "Make people laugh", optionB: "Make people think deeply", followUp: "What conversations do you enjoy most?", active: true },

      // Social (23 questions)
      { text: "Would you rather", category: "social", optionA: "Host parties every weekend", optionB: "Attend parties every weekend", followUp: "What's your ideal weekend?", active: true },
      { text: "Would you rather", category: "social", optionA: "Remember everyone you meet", optionB: "Have everyone remember you", followUp: "What makes someone memorable?", active: true },
      { text: "Would you rather", category: "social", optionA: "Give the best advice", optionB: "Tell the best stories", followUp: "What story do you love to tell?", active: true },
      { text: "Would you rather", category: "social", optionA: "Throw surprise parties", optionB: "Plan elaborate events", followUp: "What's the best party you've been to?", active: true },
      { text: "Would you rather", category: "social", optionA: "Always diffuse arguments", optionB: "Always win arguments", followUp: "How do you handle disagreements?", active: true },
      { text: "Would you rather", category: "social", optionA: "Start conversations easily", optionB: "End conversations gracefully", followUp: "What makes a good conversation?", active: true },
      { text: "Would you rather", category: "social", optionA: "Plan hangouts", optionB: "Go with the flow", followUp: "What's your ideal hangout?", active: true },
      { text: "Would you rather", category: "social", optionA: "Mediate conflicts", optionB: "Celebrate victories", followUp: "What role do you play in your friend group?", active: true },
      { text: "Would you rather", category: "social", optionA: "Bring people together", optionB: "Help people find themselves", followUp: "What's your role in relationships?", active: true },
      { text: "Would you rather", category: "social", optionA: "Give great compliments", optionB: "Give great advice", followUp: "What do people come to you for?", active: true },
      { text: "Would you rather", category: "social", optionA: "Comfort people when they're sad", optionB: "Motivate people when they're stuck", followUp: "How do you help others?", active: true },
      { text: "Would you rather", category: "social", optionA: "Be the person everyone trusts", optionB: "Be the person everyone admires", followUp: "What qualities do you value in others?", active: true },
      { text: "Would you rather", category: "social", optionA: "Organize community events", optionB: "Volunteer for causes", followUp: "What cause matters to you?", active: true },
      { text: "Would you rather", category: "social", optionA: "Know everyone's birthday", optionB: "Never forget a face", followUp: "What helps you remember people?", active: true },
      { text: "Would you rather", category: "social", optionA: "Recognize everyone you've met", optionB: "Be recognized by everyone you've met", followUp: "What makes you memorable?", active: true },
      { text: "Would you rather", category: "social", optionA: "Be able to talk to animals", optionB: "Be able to speak all languages", followUp: "What would you say first?", active: true },
      { text: "Would you rather", category: "social", optionA: "Always know when someone is lying", optionB: "Always get away with lying", followUp: "How important is honesty to you?", active: true },
      { text: "Would you rather", category: "social", optionA: "Be famous but have no privacy", optionB: "Be unknown but have complete freedom", followUp: "What matters most to you in life?", active: true },
      { text: "Would you rather", category: "entertainment", optionA: "Only watch movies", optionB: "Only watch TV series", followUp: "What's your all-time favorite?", active: true },
      { text: "Would you rather", category: "entertainment", optionA: "Binge-watch a whole series", optionB: "Read an entire book series", followUp: "What's the last thing you binged?", active: true },
      { text: "Would you rather", category: "entertainment", optionA: "Star in a comedy", optionB: "Star in an action movie", followUp: "What's your favorite movie genre?", active: true },
      { text: "Would you rather", category: "entertainment", optionA: "Go to the theater every month", optionB: "Go to sporting events every month", followUp: "What's your favorite live event?", active: true },
      { text: "Would you rather", category: "entertainment", optionA: "Only watch animated shows", optionB: "Only watch live-action shows", followUp: "What show are you watching now?", active: true },

      // Entertainment (23 questions)
      { text: "Would you rather", category: "entertainment", optionA: "Watch only documentaries", optionB: "Watch only fiction", followUp: "What's something new you learned recently?", active: true },
      { text: "Would you rather", category: "entertainment", optionA: "Play video games competitively", optionB: "Play board games socially", followUp: "What's your favorite game?", active: true },
      { text: "Would you rather", category: "entertainment", optionA: "Act in theater", optionB: "Act in movies", followUp: "Would you rather perform or be behind the scenes?", active: true },
      { text: "Would you rather", category: "entertainment", optionA: "Marathon sci-fi movies", optionB: "Marathon fantasy movies", followUp: "What's your favorite movie series?", active: true },
      { text: "Would you rather", category: "entertainment", optionA: "Watch horror movies", optionB: "Watch romance movies", followUp: "What movie genre do you avoid?", active: true },
      { text: "Would you rather", category: "entertainment", optionA: "Collect movie memorabilia", optionB: "Collect sports memorabilia", followUp: "What would you want signed?", active: true },
      { text: "Would you rather", category: "entertainment", optionA: "Review movies professionally", optionB: "Review restaurants professionally", followUp: "What would you critique?", active: true },
      { text: "Would you rather", category: "entertainment", optionA: "Voice act in animations", optionB: "Motion capture for games", followUp: "What character would you want to bring to life?", active: true },
      { text: "Would you rather", category: "entertainment", optionA: "Write screenplays", optionB: "Write TV episodes", followUp: "What story would you tell?", active: true },
      { text: "Would you rather", category: "entertainment", optionA: "Create podcasts", optionB: "Create YouTube videos", followUp: "What content do you consume?", active: true },
      { text: "Would you rather", category: "entertainment", optionA: "Attend movie premieres", optionB: "Attend game launches", followUp: "What release are you excited for?", active: true },
      { text: "Would you rather", category: "entertainment", optionA: "Binge entire series in one sitting", optionB: "Savor one episode at a time", followUp: "How do you consume content?", active: true },
      { text: "Would you rather", category: "entertainment", optionA: "Have backstage passes for life", optionB: "Have front row seats for life", followUp: "What show would you want to see?", active: true },
      { text: "Would you rather", category: "entertainment", optionA: "Live in your favorite movie", optionB: "Live in your favorite video game", followUp: "Which one would you choose?", active: true },
      { text: "Would you rather", category: "entertainment", optionA: "Read minds", optionB: "Teleport anywhere", followUp: "How would you use that power?", active: true },
      { text: "Would you rather", category: "preferences", optionA: "Always know the truth", optionB: "Live in blissful ignorance", followUp: "Do you prefer honesty or kindness?", active: true },
      { text: "Would you rather", category: "preferences", optionA: "Wear only bright colors", optionB: "Wear only dark colors", followUp: "What's your style?", active: true },
      { text: "Would you rather", category: "preferences", optionA: "Live without heating", optionB: "Live without air conditioning", followUp: "What's your comfort zone?", active: true },
      { text: "Would you rather", category: "preferences", optionA: "Always be overdressed", optionB: "Always be underdressed", followUp: "What's your go-to outfit?", active: true },
      { text: "Would you rather", category: "preferences", optionA: "Always have perfect hair", optionB: "Always have perfect skin", followUp: "What's your self-care routine?", active: true },
      { text: "Would you rather", category: "preferences", optionA: "Live in silence", optionB: "Live with constant noise", followUp: "What sounds do you find soothing?", active: true },
      { text: "Would you rather", category: "preferences", optionA: "Never feel pain", optionB: "Never feel fear", followUp: "What emotion is most useful?", active: true },
      { text: "Would you rather", category: "preferences", optionA: "Wear only comfortable shoes", optionB: "Wear only stylish shoes", followUp: "What's your shoe style?", active: true },

      // Preferences (23 questions)
      { text: "Would you rather", category: "preferences", optionA: "Always have wet socks", optionB: "Always have sweaty hands", followUp: "What small annoyance bothers you most?", active: true },
      { text: "Would you rather", category: "preferences", optionA: "Read physical books only", optionB: "Read digital books only", followUp: "What are you reading now?", active: true },
      { text: "Would you rather", category: "preferences", optionA: "Shower in the morning", optionB: "Shower at night", followUp: "What's your routine?", active: true },
      { text: "Would you rather", category: "preferences", optionA: "Wear summer clothes year-round", optionB: "Wear winter clothes year-round", followUp: "What's your clothing style?", active: true },
      { text: "Would you rather", category: "preferences", optionA: "Take cold showers", optionB: "Take hot baths", followUp: "How do you unwind?", active: true },
      { text: "Would you rather", category: "preferences", optionA: "Drink only water", optionB: "Never drink water (only other beverages)", followUp: "What's your favorite drink?", active: true },
      { text: "Would you rather", category: "preferences", optionA: "Only use a flip phone", optionB: "Only use a tablet", followUp: "What tech do you use most?", active: true },
      { text: "Would you rather", category: "preferences", optionA: "Listen to audiobooks", optionB: "Read ebooks", followUp: "How do you prefer to read?", active: true },
      { text: "Would you rather", category: "preferences", optionA: "Never use social media again", optionB: "Never watch another movie/show", followUp: "How much time do you spend on screens?", active: true },
      { text: "Would you rather", category: "preferences", optionA: "Never have to sleep", optionB: "Never have to eat", followUp: "What would you do with the extra time?", active: true },
      { text: "Would you rather", category: "preferences", optionA: "Live without music", optionB: "Live without movies", followUp: "What's your go-to mood booster?", active: true },
      { text: "Would you rather", category: "time", optionA: "Know your future", optionB: "Change your past", followUp: "What advice would you give your younger self?", active: true },
      { text: "Would you rather", category: "time", optionA: "Live the same year twice", optionB: "Skip ahead one year", followUp: "What's your favorite year so far?", active: true },
      { text: "Would you rather", category: "time", optionA: "Experience all four seasons", optionB: "Live in eternal spring", followUp: "What's your favorite season activity?", active: true },
      { text: "Would you rather", category: "time", optionA: "Watch history unfold", optionB: "Shape the future", followUp: "What historical event would you witness?", active: true },
      { text: "Would you rather", category: "time", optionA: "Be stuck in a time loop", optionB: "Age twice as fast", followUp: "What would you do with extra time?", active: true },
      { text: "Would you rather", category: "time", optionA: "See 24 hours into the future", optionB: "See 24 hours into the past", followUp: "What would you check on?", active: true },
      { text: "Would you rather", category: "time", optionA: "Relive childhood summers", optionB: "Fast forward to retirement", followUp: "What age has been your favorite?", active: true },
      { text: "Would you rather", category: "time", optionA: "Experience different time periods for a day each", optionB: "Live in one time period forever", followUp: "What's the most interesting time period?", active: true },
      { text: "Would you rather", category: "time", optionA: "Slow down time for yourself", optionB: "Speed up time for yourself", followUp: "What would you do with that ability?", active: true },
      { text: "Would you rather", category: "time", optionA: "Remember every moment", optionB: "Forget bad memories", followUp: "What's your favorite memory?", active: true },
      { text: "Would you rather", category: "time", optionA: "Record your entire life", optionB: "Forget things you want to forget", followUp: "What would you want to remember forever?", active: true },
      { text: "Would you rather", category: "time", optionA: "Experience the Renaissance", optionB: "Experience the Space Age", followUp: "What era of innovation interests you?", active: true },

      // Pets (23 questions)
      { text: "Would you rather", category: "pets", optionA: "Have a pet that lives forever", optionB: "Have many different pets over time", followUp: "What's your dream pet?", active: true },
      { text: "Would you rather", category: "pets", optionA: "Have a talking parrot", optionB: "Have a protective guard dog", followUp: "What would you teach your pet?", active: true },
      { text: "Would you rather", category: "pets", optionA: "Have pets that do tricks", optionB: "Have pets that cuddle", followUp: "What's the best thing about pets?", active: true },
      { text: "Would you rather", category: "pets", optionA: "Have a pet owl", optionB: "Have a pet fox", followUp: "What unusual pet would you want?", active: true },
      { text: "Would you rather", category: "pets", optionA: "Have a miniature pet", optionB: "Have a giant pet", followUp: "What size pet would be ideal?", active: true },
      { text: "Would you rather", category: "pets", optionA: "Have a pet sloth", optionB: "Have a pet otter", followUp: "What animal personality matches yours?", active: true },
      { text: "Would you rather", category: "pets", optionA: "Train animals for movies", optionB: "Rescue and rehabilitate animals", followUp: "What's your relationship with animals?", active: true },
      { text: "Would you rather", category: "pets", optionA: "Have pets that live as long as you", optionB: "Have many different pets throughout life", followUp: "What makes pets special?", active: true },
      { text: "Would you rather", category: "pets", optionA: "Have a pet that alerts you to danger", optionB: "Have a pet that finds lost things", followUp: "What would you want your pet to help with?", active: true },
      { text: "Would you rather", category: "pets", optionA: "Have a pet monkey", optionB: "Have a pet penguin", followUp: "What pet would surprise people?", active: true },
      { text: "Would you rather", category: "pets", optionA: "Have a pet that's always happy", optionB: "Have a pet that understands you", followUp: "What do you love about animals?", active: true },
      { text: "Would you rather", category: "pets", optionA: "Have a pet that does chores", optionB: "Have a pet that tells jokes", followUp: "What's the funniest thing a pet has done?", active: true },
      { text: "Would you rather", category: "pets", optionA: "Have a hypoallergenic pet", optionB: "Have an exotic pet", followUp: "What stops you from having a pet?", active: true },
      { text: "Would you rather", category: "pets", optionA: "Have a pet that fetches anything", optionB: "Have a pet that guards everything", followUp: "What would you want your pet to do?", active: true },
      { text: "Would you rather", category: "pets", optionA: "Walk dogs professionally", optionB: "Pet sit professionally", followUp: "What animal job would you want?", active: true },
      { text: "Would you rather", category: "pets", optionA: "Have a dog", optionB: "Have a cat", followUp: "Do you have any pets?", active: true },
      { text: "Would you rather", category: "sports", optionA: "Compete in the Olympics", optionB: "Perform at a major music festival", followUp: "What would you compete in or perform?", active: true },
      { text: "Would you rather", category: "sports", optionA: "Play professional basketball", optionB: "Play professional soccer", followUp: "What sport do you enjoy watching most?", active: true },
      { text: "Would you rather", category: "sports", optionA: "Snowboard down mountains", optionB: "Surf big waves", followUp: "What's the most exciting physical activity you've tried?", active: true },
      { text: "Would you rather", category: "sports", optionA: "Win a championship as a team", optionB: "Win a championship solo", followUp: "Do you prefer team or individual activities?", active: true },
      { text: "Would you rather", category: "sports", optionA: "Play extreme sports", optionB: "Play strategic board games", followUp: "How competitive are you?", active: true },
      { text: "Would you rather", category: "sports", optionA: "Try parkour", optionB: "Try rock climbing", followUp: "What physical challenge interests you?", active: true },
      { text: "Would you rather", category: "sports", optionA: "Play in the NBA", optionB: "Play in the NFL", followUp: "What sport do you play?", active: true },

      // Sports (23 questions)
      { text: "Would you rather", category: "sports", optionA: "Coach a team to victory", optionB: "Win as a player", followUp: "Have you ever been on a team?", active: true },
      { text: "Would you rather", category: "sports", optionA: "Do gymnastics", optionB: "Do martial arts", followUp: "What physical activity challenges you?", active: true },
      { text: "Would you rather", category: "sports", optionA: "Skateboard professionally", optionB: "BMX professionally", followUp: "What action sports interest you?", active: true },
      { text: "Would you rather", category: "sports", optionA: "Play ultimate frisbee", optionB: "Play dodgeball", followUp: "What's your favorite PE activity?", active: true },
      { text: "Would you rather", category: "sports", optionA: "Try ice hockey", optionB: "Try lacrosse", followUp: "What new sport would you try?", active: true },
      { text: "Would you rather", category: "sports", optionA: "Perfect your golf swing", optionB: "Perfect your tennis serve", followUp: "What skill would you perfect?", active: true },
      { text: "Would you rather", category: "sports", optionA: "Bowl a perfect game", optionB: "Throw a perfect dart game", followUp: "What precision sport interests you?", active: true },
      { text: "Would you rather", category: "sports", optionA: "Play water polo", optionB: "Play volleyball", followUp: "What team sport do you enjoy?", active: true },
      { text: "Would you rather", category: "sports", optionA: "Coach little league", optionB: "Referee professional games", followUp: "What's your relationship with sports?", active: true },
      { text: "Would you rather", category: "sports", optionA: "Play disc golf", optionB: "Play mini golf", followUp: "What casual sport do you enjoy?", active: true },
      { text: "Would you rather", category: "creativity", optionA: "Write a bestselling novel", optionB: "Direct a blockbuster movie", followUp: "What story would you tell?", active: true },
      { text: "Would you rather", category: "creativity", optionA: "Design video games", optionB: "Design fashion", followUp: "What inspires your creativity?", active: true },
      { text: "Would you rather", category: "creativity", optionA: "Compose a symphony", optionB: "Choreograph a ballet", followUp: "What art form moves you most?", active: true },
      { text: "Would you rather", category: "creativity", optionA: "Paint a masterpiece", optionB: "Sculpt a masterpiece", followUp: "What creative project would you start?", active: true },
      { text: "Would you rather", category: "creativity", optionA: "Illustrate children's books", optionB: "Design album covers", followUp: "What inspires you?", active: true },
      { text: "Would you rather", category: "creativity", optionA: "Write poetry", optionB: "Write lyrics", followUp: "What's your favorite quote?", active: true },
      { text: "Would you rather", category: "creativity", optionA: "Create viral videos", optionB: "Create viral memes", followUp: "What makes content shareable?", active: true },
      { text: "Would you rather", category: "creativity", optionA: "Animate cartoons", optionB: "Design characters", followUp: "What's your favorite animated movie?", active: true },
      { text: "Would you rather", category: "creativity", optionA: "Design buildings", optionB: "Design products", followUp: "What would you create?", active: true },
      { text: "Would you rather", category: "creativity", optionA: "Design tattoos", optionB: "Design jewelry", followUp: "What art form interests you?", active: true },
      { text: "Would you rather", category: "creativity", optionA: "Design logos and branding", optionB: "Design user interfaces", followUp: "What design catches your eye?", active: true },
      { text: "Would you rather", category: "creativity", optionA: "Design theme park rides", optionB: "Design escape rooms", followUp: "What experience would you create?", active: true },
      { text: "Would you rather", category: "creativity", optionA: "Sculpt with clay", optionB: "Carve wood", followUp: "What material would you work with?", active: true },

      // Creativity (remaining)
      { text: "Would you rather", category: "creativity", optionA: "Make pottery", optionB: "Blow glass", followUp: "What craft would you try?", active: true },
      { text: "Would you rather", category: "creativity", optionA: "Create stop-motion animation", optionB: "Create time-lapse photography", followUp: "What visual medium interests you?", active: true },
      { text: "Would you rather", category: "creativity", optionA: "Graffiti art", optionB: "Street performance", followUp: "What public art inspires you?", active: true },
      { text: "Would you rather", category: "creativity", optionA: "Perform spoken word poetry", optionB: "Write graphic novels", followUp: "What medium fits your voice?", active: true },
      { text: "Would you rather", category: "travel", optionA: "Visit every country in Europe", optionB: "Visit every country in Asia", followUp: "Where have you always wanted to go?", active: true },
      { text: "Would you rather", category: "travel", optionA: "Road trip across your country", optionB: "Backpack across another continent", followUp: "What's the best trip you've taken?", active: true },
      { text: "Would you rather", category: "travel", optionA: "Stay in luxury hotels", optionB: "Stay with local families", followUp: "What's your travel style?", active: true },
      { text: "Would you rather", category: "travel", optionA: "Take a cruise around the world", optionB: "Take a train across continents", followUp: "What's your preferred way to travel?", active: true },
      { text: "Would you rather", category: "travel", optionA: "Visit ancient historical sites", optionB: "Visit modern architectural marvels", followUp: "What place has the best history?", active: true },
      { text: "Would you rather", category: "travel", optionA: "Travel solo", optionB: "Travel with a group", followUp: "Who would you want to travel with?", active: true },
      { text: "Would you rather", category: "travel", optionA: "Visit tropical islands", optionB: "Visit snowy mountains", followUp: "What climate do you prefer?", active: true },
      { text: "Would you rather", category: "travel", optionA: "Travel by plane", optionB: "Travel by train", followUp: "What's the journey like for you?", active: true },
      { text: "Would you rather", category: "travel", optionA: "Go on a safari", optionB: "Go on a food tour", followUp: "What kind of experiences do you seek?", active: true },
      { text: "Would you rather", category: "travel", optionA: "Visit all the wonders of the ancient world", optionB: "Visit all the wonders of the modern world", followUp: "What landmark amazes you?", active: true },
      { text: "Would you rather", category: "travel", optionA: "Travel in an RV", optionB: "Travel backpacking", followUp: "What's your travel essential?", active: true },
      { text: "Would you rather", category: "travel", optionA: "See all UNESCO World Heritage sites", optionB: "See all national parks", followUp: "What natural or cultural site amazes you?", active: true },
      { text: "Would you rather", category: "travel", optionA: "Take a gap year to travel", optionB: "Take short trips frequently", followUp: "What's your ideal travel schedule?", active: true },
      { text: "Would you rather", category: "travel", optionA: "Travel to learn languages", optionB: "Travel to try foods", followUp: "What do you seek when traveling?", active: true },
      { text: "Would you rather", category: "travel", optionA: "Stay in hostels and meet travelers", optionB: "Stay in Airbnbs and live like locals", followUp: "What kind of traveler are you?", active: true },
      { text: "Would you rather", category: "travel", optionA: "Take a river cruise", optionB: "Take a coastal cruise", followUp: "What's your ideal vacation pace?", active: true },
      { text: "Would you rather", category: "travel", optionA: "Visit every continent", optionB: "Visit every ocean", followUp: "What's on your bucket list?", active: true },
      { text: "Would you rather", category: "technology", optionA: "Invent a new app", optionB: "Invent a new gadget", followUp: "What problem would you solve?", active: true },
      { text: "Would you rather", category: "technology", optionA: "Have a personal robot assistant", optionB: "Have a self-driving car", followUp: "What tech can't you live without?", active: true },

      // Technology (remaining)
      { text: "Would you rather", category: "technology", optionA: "Never lose your phone battery", optionB: "Have unlimited data everywhere", followUp: "What do you use your phone for most?", active: true },
      { text: "Would you rather", category: "technology", optionA: "Live with 90s technology", optionB: "Live with technology from 2050", followUp: "What old tech do you miss?", active: true },
      { text: "Would you rather", category: "technology", optionA: "Control all devices with your mind", optionB: "Never need to charge any device", followUp: "What technology amazes you?", active: true },
      { text: "Would you rather", category: "technology", optionA: "Have AI do all your homework", optionB: "Have AI do all your chores", followUp: "What task would you delegate?", active: true },
      { text: "Would you rather", category: "technology", optionA: "Have holographic displays everywhere", optionB: "Have virtual reality on demand", followUp: "What tech do you wish existed?", active: true },
      { text: "Would you rather", category: "technology", optionA: "Code video games", optionB: "Code websites", followUp: "Have you tried coding?", active: true },
      { text: "Would you rather", category: "technology", optionA: "3D print anything", optionB: "Edit photos perfectly", followUp: "What would you create?", active: true },
      { text: "Would you rather", category: "technology", optionA: "Beta test new games", optionB: "Beta test new apps", followUp: "What features do you look for?", active: true },
      { text: "Would you rather", category: "technology", optionA: "Stream your life 24/7", optionB: "Never appear online", followUp: "What's your relationship with social media?", active: true },
      { text: "Would you rather", category: "technology", optionA: "Build computers", optionB: "Build drones", followUp: "What technology do you understand?", active: true },
      { text: "Would you rather", category: "technology", optionA: "Design smart home systems", optionB: "Design wearable tech", followUp: "What tech makes life better?", active: true },
      { text: "Would you rather", category: "technology", optionA: "Have perfect WiFi everywhere", optionB: "Have unlimited cloud storage", followUp: "What tech limitation annoys you?", active: true },
      { text: "Would you rather", category: "technology", optionA: "Access any database", optionB: "Communicate with any device", followUp: "What information would you seek?", active: true },
      { text: "Would you rather", category: "technology", optionA: "Have augmented reality glasses", optionB: "Have a neural interface", followUp: "What future tech excites you?", active: true },
      { text: "Would you rather", category: "technology", optionA: "Have a smart assistant that's actually helpful", optionB: "Have devices that never malfunction", followUp: "What tech frustrates you?", active: true },
      { text: "Would you rather", category: "science", optionA: "Discover a new planet", optionB: "Discover a cure for a disease", followUp: "What scientific mystery fascinates you?", active: true },
      { text: "Would you rather", category: "science", optionA: "Study marine biology", optionB: "Study astronomy", followUp: "What science topic interests you most?", active: true },
      { text: "Would you rather", category: "science", optionA: "Clone extinct animals", optionB: "Create new hybrid animals", followUp: "What extinct animal would you bring back?", active: true },
      { text: "Would you rather", category: "science", optionA: "Visit the International Space Station", optionB: "Dive to the ocean floor", followUp: "What scientific discovery excites you?", active: true },
      { text: "Would you rather", category: "science", optionA: "Understand how everything works", optionB: "Invent something completely new", followUp: "What makes you curious?", active: true },
      { text: "Would you rather", category: "science", optionA: "Study the human brain", optionB: "Study the cosmos", followUp: "What do you wonder about?", active: true },
      { text: "Would you rather", category: "science", optionA: "Work with chemicals", optionB: "Work with technology", followUp: "What career interests you?", active: true },
      { text: "Would you rather", category: "science", optionA: "Mix chemicals in a lab", optionB: "Program in a tech lab", followUp: "What experiments interest you?", active: true },

      // Science (remaining)
      { text: "Would you rather", category: "science", optionA: "Study genetics", optionB: "Study robotics", followUp: "What scientific field excites you?", active: true },
      { text: "Would you rather", category: "science", optionA: "Study weather patterns", optionB: "Study earthquakes", followUp: "What natural force impresses you?", active: true },
      { text: "Would you rather", category: "science", optionA: "Study bioluminescence", optionB: "Study camouflage", followUp: "What natural adaptation amazes you?", active: true },
      { text: "Would you rather", category: "science", optionA: "Study particle physics", optionB: "Study quantum mechanics", followUp: "What science concept confuses you?", active: true },
      { text: "Would you rather", category: "science", optionA: "Study evolution", optionB: "Study ecology", followUp: "What natural system fascinates you?", active: true },
      { text: "Would you rather", category: "science", optionA: "Explore caves for new minerals", optionB: "Search forests for new plants", followUp: "What natural discovery would excite you?", active: true },
      { text: "Would you rather", category: "science", optionA: "Study animal behavior", optionB: "Study human psychology", followUp: "What behavior interests you?", active: true },
      { text: "Would you rather", category: "science", optionA: "Study the speed of light", optionB: "Study the speed of sound", followUp: "What physics concept interests you?", active: true },
      { text: "Would you rather", category: "science", optionA: "Understand all mathematics", optionB: "Understand all languages", followUp: "What system of knowledge interests you?", active: true },
      { text: "Would you rather", category: "fantasy", optionA: "Be a wizard", optionB: "Be a knight", followUp: "What magical ability would you want?", active: true },
      { text: "Would you rather", category: "fantasy", optionA: "Live in a magical forest", optionB: "Live in a floating castle", followUp: "What fantasy world would you visit?", active: true },
      { text: "Would you rather", category: "fantasy", optionA: "Ride a griffin", optionB: "Ride a pegasus", followUp: "Where would you fly?", active: true },
      { text: "Would you rather", category: "fantasy", optionA: "Have a magic wand", optionB: "Have a magic carpet", followUp: "What would you do with magic?", active: true },
      { text: "Would you rather", category: "fantasy", optionA: "Attend a school for wizards", optionB: "Join a guild of adventurers", followUp: "What fantasy character would you be?", active: true },
      { text: "Would you rather", category: "fantasy", optionA: "Own a magic mirror", optionB: "Own a crystal ball", followUp: "What would you want to see?", active: true },
      { text: "Would you rather", category: "fantasy", optionA: "Explore enchanted forests", optionB: "Explore mystical temples", followUp: "What fantasy setting appeals to you?", active: true },
      { text: "Would you rather", category: "fantasy", optionA: "Befriend a fairy", optionB: "Befriend a giant", followUp: "What magical creature would you want to meet?", active: true },
      { text: "Would you rather", category: "fantasy", optionA: "Cast spells with words", optionB: "Cast spells with gestures", followUp: "What spell would you cast first?", active: true },
      { text: "Would you rather", category: "fantasy", optionA: "Own a magic book of spells", optionB: "Own a sword of power", followUp: "What magical item would you want?", active: true },
      { text: "Would you rather", category: "fantasy", optionA: "Ride a phoenix", optionB: "Ride a sea serpent", followUp: "What mythical creature fascinates you?", active: true },
      { text: "Would you rather", category: "fantasy", optionA: "Have an enchanted garden", optionB: "Have a portal to other worlds", followUp: "Where would your portal go?", active: true },
      { text: "Would you rather", category: "fantasy", optionA: "Find a genie's lamp", optionB: "Find a leprechaun's gold", followUp: "What would you wish for?", active: true },

      // Fantasy (remaining)
      { text: "Would you rather", category: "fantasy", optionA: "Be immortal but not invincible", optionB: "Be invincible but age normally", followUp: "What would you do with extra time?", active: true },
      { text: "Would you rather", category: "fantasy", optionA: "Command an army of creatures", optionB: "Befriend one legendary creature", followUp: "What creature would you choose?", active: true },
      { text: "Would you rather", category: "fantasy", optionA: "Summon creatures", optionB: "Banish creatures", followUp: "What creature would you summon?", active: true },
      { text: "Would you rather", category: "fantasy", optionA: "Live in a world with magic", optionB: "Live in a world with advanced technology", followUp: "What world would you build?", active: true },
      { text: "Would you rather", category: "mystery", optionA: "Solve a famous cold case", optionB: "Discover a hidden treasure", followUp: "What mystery would you want to solve?", active: true },
      { text: "Would you rather", category: "mystery", optionA: "Be a detective", optionB: "Be a spy", followUp: "What's your favorite mystery story?", active: true },
      { text: "Would you rather", category: "mystery", optionA: "Explore ancient ruins", optionB: "Investigate paranormal activity", followUp: "Do you believe in the supernatural?", active: true },
      { text: "Would you rather", category: "mystery", optionA: "Find a secret passage in your house", optionB: "Find a treasure map", followUp: "What's the coolest thing you've discovered?", active: true },
      { text: "Would you rather", category: "mystery", optionA: "Decode ancient languages", optionB: "Crack complex codes", followUp: "What puzzle stumped you recently?", active: true },
      { text: "Would you rather", category: "mystery", optionA: "Investigate crimes", optionB: "Prevent crimes", followUp: "What's your favorite mystery movie?", active: true },
      { text: "Would you rather", category: "mystery", optionA: "Solve riddles", optionB: "Create riddles", followUp: "What's a riddle you know?", active: true },
      { text: "Would you rather", category: "mystery", optionA: "Be a forensic scientist", optionB: "Be a private investigator", followUp: "What mysteries intrigue you?", active: true },
      { text: "Would you rather", category: "mystery", optionA: "Uncover conspiracies", optionB: "Expose secrets", followUp: "What mystery keeps you curious?", active: true },
      { text: "Would you rather", category: "mystery", optionA: "Discover Atlantis", optionB: "Find El Dorado", followUp: "What lost place intrigues you?", active: true },
      { text: "Would you rather", category: "mystery", optionA: "Explore the Bermuda Triangle", optionB: "Explore Area 51", followUp: "What conspiracy theory interests you?", active: true },
      { text: "Would you rather", category: "mystery", optionA: "Read minds but not control them", optionB: "Control actions but not read minds", followUp: "What would you want to know?", active: true },
      { text: "Would you rather", category: "mystery", optionA: "Time travel to witness history", optionB: "Visit parallel universes", followUp: "What would you want to see?", active: true },
      { text: "Would you rather", category: "mystery", optionA: "Know every secret", optionB: "Keep every secret", followUp: "What's the best secret you've kept?", active: true },
      { text: "Would you rather", category: "mystery", optionA: "Investigate urban legends", optionB: "Debunk myths", followUp: "What mystery captivates you?", active: true },
      { text: "Would you rather", category: "mystery", optionA: "Explore haunted locations", optionB: "Document unexplained phenomena", followUp: "What unexplained event interests you?", active: true },
      { text: "Would you rather", category: "music", optionA: "Front a rock band", optionB: "Be a solo pop star", followUp: "What's your favorite music genre?", active: true },
      { text: "Would you rather", category: "music", optionA: "Go to music festivals all summer", optionB: "Attend intimate concerts all year", followUp: "What's the best concert you've been to?", active: true },
      { text: "Would you rather", category: "music", optionA: "Create your own music genre", optionB: "Master every existing genre", followUp: "What song is stuck in your head right now?", active: true },

      // Music (remaining)
      { text: "Would you rather", category: "music", optionA: "Have perfect pitch", optionB: "Have perfect rhythm", followUp: "Do you play any instruments?", active: true },
      { text: "Would you rather", category: "music", optionA: "DJ at major events", optionB: "Conduct an orchestra", followUp: "What's your pump-up song?", active: true },
      { text: "Would you rather", category: "music", optionA: "Remix classic songs", optionB: "Write original songs", followUp: "What song do you never skip?", active: true },
      { text: "Would you rather", category: "music", optionA: "Sing backup for famous artists", optionB: "Be a famous solo artist", followUp: "Who would you want to perform with?", active: true },
      { text: "Would you rather", category: "music", optionA: "Rap battle champion", optionB: "Karaoke champion", followUp: "What song would you perform?", active: true },
      { text: "Would you rather", category: "music", optionA: "Attend a music awards show", optionB: "Perform at a music awards show", followUp: "What music achievement would you want?", active: true },
      { text: "Would you rather", category: "music", optionA: "Sample old records", optionB: "Create new sounds", followUp: "What music production interests you?", active: true },
      { text: "Would you rather", category: "music", optionA: "Play at coffee shops", optionB: "Play at stadiums", followUp: "What's your ideal audience size?", active: true },
      { text: "Would you rather", category: "music", optionA: "Discover new artists before they're famous", optionB: "See legendary artists in their prime", followUp: "What artist do you wish you could have seen live?", active: true },
      { text: "Would you rather", category: "music", optionA: "Have your song go viral", optionB: "Have your song on the radio", followUp: "What would your song be about?", active: true },
      { text: "Would you rather", category: "music", optionA: "Curate playlists for others", optionB: "Have others curate playlists for you", followUp: "What playlist do you have?", active: true },
      { text: "Would you rather", category: "music", optionA: "Produce hit albums", optionB: "Engineer perfect sound", followUp: "What's your favorite album?", active: true },
      { text: "Would you rather", category: "music", optionA: "Teach music to kids", optionB: "Perform for audiences", followUp: "What role does music play in your life?", active: true },
      { text: "Would you rather", category: "music", optionA: "Have a song written about you", optionB: "Write a song about someone", followUp: "What would the song be about?", active: true },
      { text: "Would you rather", category: "hobbies", optionA: "Build things with your hands", optionB: "Create digital art", followUp: "What do you do for fun?", active: true },
      { text: "Would you rather", category: "hobbies", optionA: "Collect rare items", optionB: "Create original art", followUp: "Do you collect anything?", active: true },
      { text: "Would you rather", category: "hobbies", optionA: "Perfect your photography skills", optionB: "Perfect your cooking skills", followUp: "What hobby brings you joy?", active: true },
      { text: "Would you rather", category: "hobbies", optionA: "Garden and grow your own food", optionB: "Build and fix things yourself", followUp: "What's a skill you want to learn?", active: true },
      { text: "Would you rather", category: "hobbies", optionA: "Restore old cars", optionB: "Restore old furniture", followUp: "Do you like fixing things?", active: true },
      { text: "Would you rather", category: "hobbies", optionA: "Knit or crochet", optionB: "Sew or embroider", followUp: "Have you made something you're proud of?", active: true },
      { text: "Would you rather", category: "hobbies", optionA: "Play chess at a high level", optionB: "Play poker at a high level", followUp: "What strategy games do you enjoy?", active: true },
      { text: "Would you rather", category: "hobbies", optionA: "Learn origami", optionB: "Learn calligraphy", followUp: "What craft would you try?", active: true },

      // Hobbies (remaining)
      { text: "Would you rather", category: "hobbies", optionA: "Fly drones", optionB: "Build model rockets", followUp: "What hobbies interest you?", active: true },
      { text: "Would you rather", category: "hobbies", optionA: "Solve jigsaw puzzles", optionB: "Build LEGO sets", followUp: "What do you do to relax?", active: true },
      { text: "Would you rather", category: "hobbies", optionA: "Collect vinyl records", optionB: "Collect comic books", followUp: "What do you collect?", active: true },
      { text: "Would you rather", category: "hobbies", optionA: "Learn magic tricks", optionB: "Learn card tricks", followUp: "What skill impresses you?", active: true },
      { text: "Would you rather", category: "hobbies", optionA: "Restore antiques", optionB: "Upcycle modern items", followUp: "What old thing would you bring back?", active: true },
      { text: "Would you rather", category: "hobbies", optionA: "Race RC cars", optionB: "Race go-karts", followUp: "What speed activities interest you?", active: true },
      { text: "Would you rather", category: "hobbies", optionA: "Woodworking projects", optionB: "Metalworking projects", followUp: "What would you make?", active: true },
      { text: "Would you rather", category: "hobbies", optionA: "Customize cars", optionB: "Customize bikes", followUp: "What would you customize?", active: true },
      { text: "Would you rather", category: "hobbies", optionA: "Master chess", optionB: "Master Go", followUp: "What strategy game interests you?", active: true },
      { text: "Would you rather", category: "superpowers", optionA: "Breathe underwater", optionB: "Never need to breathe", followUp: "What underwater place would you explore?", active: true },
      { text: "Would you rather", category: "superpowers", optionA: "Heal any injury instantly", optionB: "Never get sick", followUp: "How do you take care of yourself?", active: true },
      { text: "Would you rather", category: "superpowers", optionA: "Control time", optionB: "Control minds", followUp: "How would you use that responsibility?", active: true },
      { text: "Would you rather", category: "superpowers", optionA: "Transform into any animal", optionB: "Transform into any person", followUp: "What would you transform into first?", active: true },
      { text: "Would you rather", category: "superpowers", optionA: "See through walls", optionB: "Walk through walls", followUp: "What would you explore?", active: true },
      { text: "Would you rather", category: "superpowers", optionA: "Generate force fields", optionB: "Shoot energy beams", followUp: "How would you protect others?", active: true },
      { text: "Would you rather", category: "superpowers", optionA: "Absorb knowledge from books by touching them", optionB: "Learn any skill by watching once", followUp: "What would you learn first?", active: true },
      { text: "Would you rather", category: "superpowers", optionA: "Duplicate yourself", optionB: "Be in two places at once", followUp: "What would you do with the extra you?", active: true },
      { text: "Would you rather", category: "superpowers", optionA: "Have night vision", optionB: "Have enhanced hearing", followUp: "Which sense would you enhance?", active: true },
      { text: "Would you rather", category: "superpowers", optionA: "Phase through objects", optionB: "Stick to any surface", followUp: "Where would you go?", active: true },
      { text: "Would you rather", category: "superpowers", optionA: "Create illusions", optionB: "See through illusions", followUp: "What illusion would you create?", active: true },
      { text: "Would you rather", category: "superpowers", optionA: "Summon objects to your hand", optionB: "Push objects away from you", followUp: "What would you summon?", active: true },
      { text: "Would you rather", category: "superpowers", optionA: "Manipulate probability", optionB: "Manipulate gravity", followUp: "What would you change?", active: true },

      // Superpowers (remaining)
      { text: "Would you rather", category: "superpowers", optionA: "Turn invisible in darkness", optionB: "Glow in the dark", followUp: "When would you use that power?", active: true },
      { text: "Would you rather", category: "superpowers", optionA: "Control electricity", optionB: "Control magnetism", followUp: "What would you power?", active: true },
      { text: "Would you rather", category: "superpowers", optionA: "Generate unlimited energy", optionB: "Create matter from nothing", followUp: "What would you create?", active: true },
      { text: "Would you rather", category: "superpowers", optionA: "Create pocket dimensions", optionB: "Travel between dimensions", followUp: "What would your dimension be like?", active: true },
      { text: "Would you rather", category: "superpowers", optionA: "Control fire", optionB: "Control water", followUp: "What would you do with that power?", active: true },
      { text: "Would you rather", category: "superpowers", optionA: "Fly", optionB: "Be invisible", followUp: "Where would you go first?", active: true },
      { text: "Would you rather", category: "superpowers", optionA: "Super strength", optionB: "Super speed", followUp: "Who's your favorite superhero?", active: true },
      { text: "Would you rather", category: "time", optionA: "Time travel to meet your ancestors", optionB: "Time travel to meet your descendants", followUp: "What would you want to know?", active: true },
      { text: "Would you rather", category: "time", optionA: "Live through every historical era for a year", optionB: "Jump to different futures for a day each", followUp: "What time period intrigues you most?", active: true },
      { text: "Would you rather", category: "time", optionA: "Live one day as every person on Earth", optionB: "Live 1000 years as yourself", followUp: "What would you want to experience?", active: true },
      { text: "Would you rather", category: "preferences", optionA: "Always be stuck in traffic", optionB: "Always have a slow internet connection", followUp: "What tests your patience the most?", active: true },
    ];

    for (const question of bulkQuestions) {
      await ctx.db.insert("questions", question);
    }

    return { message: `Added ${bulkQuestions.length} new questions! Total questions in database: ${existingCount + bulkQuestions.length}` };
  },
});
